### ISSUE TITLE
asctime is not logged

### ISSUE THREAD

**Issue by ozooner** [joaodrp/gelf-formatter#4] opened 2019-12-18 10:52 UTC
Hi!

Firsly gelf-formatter is awesome, I don't understand how other projects even justify blocking entire program execution to send logs over network...

WIth that said, tailing logs on server is bit more complicated with gelf format and I wanted to add a human readable timestamp. Fortunately this awesome library supports adding `allowed_reserved_attrs`, however `asctime` does not seem to work, whereas other attributes work.

This is the configuration:
`gelf_formatter = GelfFormatter(allowed_reserved_attrs=["processName", "asctime", "filename", "created"]`

Log line:
`{"version": "1.1", "short_message": "beat: Waking up in 5.00 minutes.", "timestamp": 1576665042.5591564, "level": 7, "host": "playsignage-int-2019", "_filename": "beat.py", "_created": 1576665042.5591564, "_processName": "MainProcess"}`

The log line contains extra attrs, such as _processName, _filename and _created, however **asctime** is missing...any ideas?

**Comment by ozooner** [comment] 2019-12-18 11:27
It seems that `message` is also not printed in the log message, perhaps related to this: https://stackoverflow.com/questions/32301522/logrecord-does-not-have-expected-fields

**Comment by girstenbrei** [comment] 2019-12-20 07:51
@ozooner stackoverflow seems to be right.

`message` is translated into `short_message` [here](https://github.com/joaodrp/gelf-formatter/blob/8c3bd97136708265b86b788e6d55823292cda2e5/gelfformatter/formatter.py#L116) and formatting there works.

What would you expect the `asctime` field to be named? `_asctime`, `_datetime` or something configurable?

What would you expect to see in the `message` field?

Greets,
Christoph

**Comment by ozooner** [comment] 2019-12-20 10:01
I was actually only interested in the asctime field, but tried the message field to confirm that it's related to the same issue on stackoverflow.

**Comment by joaodrp** [comment] 2019-12-21 12:46
Thanks for your kind words and for raising this issue @ozooner!

Regarding `message`, it's the expected behaviour as @girstenbrei mentioned. For `asctime`, it's definitely doable and @girstenbrei already raised a PR for it: #5.

@ozooner, you mentioned that you tail the logs on the server, have you seen [gelf-pretty](https://github.com/joaodrp/gelf-pretty)? This is a tiny binary that you can drop in any machine for human readable GELF logs.

Regardless, I'll get #5 merged. Thank you all!

**Closed** 2019-12-21 12:57 UTC

**Comment by ozooner** [comment] 2019-12-22 02:21
@joaodrp - thanks for the gelf-pretty hint, had I known it before I wouldn't even have needed the asctime printout. Again, thanks for the quick help, this library in my opinion takes the **best** approach when it comes to gelf logging in python ;)
